In [6]:
import torch 
from torch.utils.data import Dataset, DataLoader
import numpy as np

In [49]:
inp = np.array(list(range(2500000)))
out = np.array(list(range(1000)))

print(inp)
inp = inp.reshape(50, 50, 1000)

#shape im height x im width x images
print(inp[:,:,0].shape)


[      0       1       2 ... 2499997 2499998 2499999]
(50, 50)


In [56]:
class Dataset2D(Dataset):   
    def __init__(self, inp, out):
        self.inp = inp
        self.out = out
        
    def __len__(self):
        return len(self.inp)

    def __getitem__(self, idx):
        sample = self.inp[:,:,idx].reshape(1, *self.inp[:,:,idx].shape)
        label = self.out[idx].reshape(1, *self.out[idx].shape)
        return sample, label

In [57]:
ds = Dataset2D(inp, out)

In [58]:
ds[0][0]

array([[[      0,    1000,    2000, ...,   47000,   48000,   49000],
        [  50000,   51000,   52000, ...,   97000,   98000,   99000],
        [ 100000,  101000,  102000, ...,  147000,  148000,  149000],
        ...,
        [2350000, 2351000, 2352000, ..., 2397000, 2398000, 2399000],
        [2400000, 2401000, 2402000, ..., 2447000, 2448000, 2449000],
        [2450000, 2451000, 2452000, ..., 2497000, 2498000, 2499000]]])

In [59]:
dl = DataLoader(ds, batch_size=20)

In [60]:
for sample, label in dl: 
    print(sample.shape)
    print(label.shape)
    break

torch.Size([20, 1, 50, 50])
torch.Size([20, 1])


In [43]:
inp[:,:,0].reshape(1, *inp[:,:,0].shape)

array([[[      0,    1000,    2000, ...,   47000,   48000,   49000],
        [  50000,   51000,   52000, ...,   97000,   98000,   99000],
        [ 100000,  101000,  102000, ...,  147000,  148000,  149000],
        ...,
        [2350000, 2351000, 2352000, ..., 2397000, 2398000, 2399000],
        [2400000, 2401000, 2402000, ..., 2447000, 2448000, 2449000],
        [2450000, 2451000, 2452000, ..., 2497000, 2498000, 2499000]]])

In [41]:
inp[:,:,0]

array([[      0,    1000,    2000, ...,   47000,   48000,   49000],
       [  50000,   51000,   52000, ...,   97000,   98000,   99000],
       [ 100000,  101000,  102000, ...,  147000,  148000,  149000],
       ...,
       [2350000, 2351000, 2352000, ..., 2397000, 2398000, 2399000],
       [2400000, 2401000, 2402000, ..., 2447000, 2448000, 2449000],
       [2450000, 2451000, 2452000, ..., 2497000, 2498000, 2499000]])

In [45]:
print(*inp[:,:,0].shape)

50 50
