In [93]:
import numpy as np 
import os 
import matplotlib.pyplot as plt
import time

import scipy
import scipy.ndimage
from scipy.ndimage import zoom

import itertools as it

In [3]:
root = "/home/ptenkaate/scratch/Master-Thesis/Dataset"
folders = os.listdir(root)
print(folders)

['original_normalized', 'scaled_normalized', 'original_normalized_rotated', 'scaled_normalized_rotated']


In [106]:
for folder in folders: 
    load_path = os.path.join(root, folder)
    
    for file in os.listdir(load_path):
        if "mask" in file:
            image = np.load(os.path.join(load_path, file))
            break
    

In [107]:
print(image.shape)

(64, 64, 24)


In [9]:
from scipy.spatial import distance

In [94]:
a = np.array([[0, 0, 0],

              [0, 0, 1],

              [0, 1, 0],

              [0, 1, 1],

              [1, 0, 0],

              [1, 0, 1],

              [1, 1, 0],

              [1, 1, 1]])

a = np.random.rand(128*128*24, 3)
print(a.shape)

b = np.random.rand(2000*4, 3)
print(a.shape)

# b = np.array([[ 0.1,  0.2,  0.4]])
t = time.time()
distance.cdist(a, b)
print(time.time() - t)

(393216, 3)
(393216, 3)
39.42471981048584


In [99]:
def get_coords(*sidelengths):
    tensors = []

    for sidelen in sidelengths:
        tensors.append(torch.linspace(0, sidelen-1, steps=sidelen))

    tensors = tuple(tensors)
    coords = torch.stack(torch.meshgrid(*tensors), dim=-1)

    return coords.reshape(-1, len(sidelengths))

In [109]:
import torch 
coords = get_coords(*image.shape).numpy()

image_flat = image.flatten()
print(image_flat.shape)
print(coords)

(98304,)
[[ 0.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  2.]
 ...
 [63. 63. 21.]
 [63. 63. 22.]
 [63. 63. 23.]]


In [102]:
printmask 

array([[[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ...,
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ...,
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [-0., -0.,  0., ...,  0.,  0.,  0.],
        ...,
        [-0., -0., -0., ..., -0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       ...,

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0., -0., ..., -0.,  0.,  0.