In [1]:
import pickle
import numpy as np 
import os

from py_files.plot_utils import *

%matplotlib qt

In [2]:
all_runs = sorted(os.listdir(path='saved_results'))
print(all_runs)

run = sorted(os.listdir(path='saved_results'))[-1]
#run = "pi_gan_2021_06_25_10_16_49"
print(run)

['pi_gan_2021_08_24_06_56_23_reconstruction_golden_cnn_run_0']
pi_gan_2021_08_24_06_56_23_reconstruction_golden_cnn_run_0


In [ ]:
with open(os.path.join("saved_results", run, "titles.pkl"), 'rb') as f:
    titles = pickle.load(f)

with open(os.path.join("saved_results", run, "images.pkl"), 'rb') as f:
    images = pickle.load(f)


In [ ]:
window = Show_images(titles, *images)

In [ ]:
mask = images[1][0]
print(mask.shape)

(128, 128, 2064)


In [ ]:
 (mask > 1).nonzero()

(array([20], dtype=int64),
 array([53], dtype=int64),
 array([1658], dtype=int64))

In [ ]:
print(mask[20, 53, 1658])

2.0
